version: '3.4'

services:
  clamav-server:
    image: mk0x/docker-clamav:alpine
    restart: unless-stopped
    networks:
      - backend
  clamav-net:
    image: ${DOCKER_REGISTRY-}clamavnet
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - clamav-server
    networks:
      - backend
networks:
  backend:
    driver: "bridge"