version: '3.4'

services:
  clamav-net:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44380
      - CLAMD_SERVER=clamav-server
      - CLAMD_SERVER_PORT=3310
      - CLAMD_SERVER_MAX_FILESIZE_MB=25
    ports:
      - "60100:80"
      - "44380:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro